language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      cache: apt
      dist: xenial

    - os: osx
      compiler: clang

env:
  global:
    - BUILD_NAME="HackRF-$TRAVIS_OS_NAME-`date --iso-8601`-$TRAVIS_COMMIT"
    - ARTEFACT_BASE=$TRAVIS_BUILD_DIR/artefacts/
    - ARTEFACT_PATH=$ARTEFACT_BASE/$BUILD_NAME

addons:
  apt:
    packages:
      - libusb-1.0-0-dev
      - libfftw3-dev
      - dfu-util
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
      - libstdc++-arm-none-eabi-newlib
      - python-yaml

  homebrew:
    taps: PX4/homebrew-px4
    packages:
       - fftw
       - gcc-arm-none-eabi
       - dfu-util

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install PyYAML; fi

before_script:
  - export CFLAGS="-Wall -Wextra -Werror"

script:
  # Host code
  - mkdir host/build
  - cd host/build
  - cmake ..
  - make
  # Firmware
  - cd ../..
  - mkdir -p $ARTEFACT_PATH/firmware-bin
  - cp firmware/cpld/sgpio_if/default.xsvf $ARTEFACT_PATH/firmware-binhackrf_cpld_default.xsvf
  - mkdir firmware/build-hackrf-one
  - mkdir firmware/build-jawbreaker
  - mkdir firmware/build-rad1o
  - cd firmware/libopencm3
  - make
  - cd ../build-hackrf-one
  - cmake ..
  - make
  - cp hackrf_usb/hackrf_usb.bin $ARTEFACT_PATH/firmware-bin/hackrf_one_usb.bin
  - cp hackrf_usb/hackrf_usb.dfu $ARTEFACT_PATH/firmware-bin/hackrf_one_usb.dfu
  - cd ../build-jawbreaker
  - cmake -DBOARD=JAWBREAKER ..
  - make
  - cp hackrf_usb/hackrf_usb.bin $ARTEFACT_PATH/firmware-bin/hackrf_jawbreaker_usb.bin
  - cp hackrf_usb/hackrf_usb.dfu $ARTEFACT_PATH/firmware-bin/hackrf_jawbreaker_usb.dfu
  - cd ../build-rad1o
  - cmake -DBOARD=RAD1O ..
  - make
  - cp hackrf_usb/hackrf_usb.bin $ARTEFACT_PATH/firmware-bin/rad1o_usb.bin
  - cp hackrf_usb/hackrf_usb.dfu $ARTEFACT_PATH/firmware-bin/rad1o_usb.dfu

deploy:
  provider: pages
  verbose: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  repo: dominicgs/Nightly-builds
  # target-branch: master
  local-dir: $ARTEFACT_BASE
  on:
    branch: travis_artefacts
