os: Visual Studio 2017
clone_depth: 1

configuration:
  - Release

environment:
  global:
    CYG_ROOT: C:\cygwin
    CYG_MIRROR: http://cygwin.mirror.constant.com
    CYG_CACHE: C:\cygwin\var\cache\setup
    CYG_BASH: C:\cygwin\bin\bash

init:
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat %PLATFORM%
install:
  # Dependencies for libHackRF
  - appveyor DownloadFile "https://github.com/libusb/libusb/releases/download/v1.0.22/libusb-1.0.22.7z" -FileName "C:\libusb.7z"
  - 7z x -y "C:\libusb.7z" -o"C:\libusb"
  - appveyor DownloadFile "http://mirrors.kernel.org/sourceware/pthreads-win32/pthreads-w32-2-9-1-release.zip" -FileName "C:\pthreads-w32-release.zip"
  - 7z x -y "C:\pthreads-w32-release.zip" -o"C:\pthreads"
  - appveyor DownloadFile "http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/pkg-config_0.26-1_win32.zip" -FileName "C:\pkg-config_win32.zip"
  - 7z x -y "C:\pkg-config_win32.zip" -o"C:\pkg-config"
  # FFTW for hackrf_sweep
  - curl -fsS -o "C:\fftw-3.3.5.zip" "ftp://ftp.fftw.org/pub/fftw/fftw-3.3.5-dll64.zip"
  - 7z x -y "C:\fftw-3.3.5.zip" -o"C:\fftw"
  - cd c:\fftw
  - ps: lib /machine:x64 /def:libfftw3f-3.def
  # ARM GCC for firmware builds
  - appveyor DownloadFile "https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-win32.zip" -FileName "C:\gcc-arm-none-eabi-7-2018-q2-update-win32.zip"
  - 7z x -y "C:\gcc-arm-none-eabi-7-2018-q2-update-win32.zip" -o"C:\gcc-arm-none-eabi"
  # Cygwin build environment for firmware
  - c:\cygwin\setup-x86.exe --quiet-mode --no-shortcuts --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_CACHE%" --packages autoconf,automake,bison,gcc-core,gcc-g++,mingw-runtime,mingw-binutils,mingw-gcc-core,mingw-gcc-g++,mingw-pthreads,mingw-w32api,libtool,make,python,gettext-devel,gettext,intltool,libiconv,pkg-config,git,curl,libxslt > NUL 2>&1'
  - '%CYG_BASH% -lc "cygcheck -dc cygwin"'
  - if not exist "make.zip" curl -L -o make.zip http://gnuwin32.sourceforge.net/downlinks/make-bin-zip.php
  - if not exist "make-dep.zip" curl -L -o make-dep.zip http://gnuwin32.sourceforge.net/downlinks/make-dep-zip.php

build_script:
  # Host library and tools
  - mkdir c:\projects\hackrf\host\build
  - cd c:\projects\hackrf\host\build
  - cmake -G "Visual Studio 14 2015 Win64" \
    -DLIBUSB_LIBRARIES="C:\libusb\MS64\dll\libusb-1.0.lib" \
    -DLIBUSB_INCLUDE_DIR="C:\libusb\include\libusb-1.0" \
    -DTHREADS_PTHREADS_INCLUDE_DIR=c:\pthreads\Pre-built.2\include \
    -DTHREADS_PTHREADS_WIN32_LIBRARY=c:\pthreads\Pre-built.2\lib\x64\pthreadVC2.lib \
    -DPKG_CONFIG_EXECUTABLE="C:\pkg-config\bin\pkg-config.exe" \
    -DFFTW_INCLUDES=C:\fftw \
    -DFFTW_LIBRARIES=C:\fftw\libfftw3f-3.lib \
    ..
  - msbuild HackRF.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  # Firmware
  - cd c:\projects\hackrf\firmware\libopencm3
  - make
  - mkdir c:\projects\hackrf\firmware\build-hackrf-one
  - cd c:\projects\hackrf\firmware\build-hackrf-one
  - cmake ..

after_build:
  - 7z a %APPVEYOR_BUILD_FOLDER%\HackRF-Windows-experimental.zip %APPVEYOR_BUILD_FOLDER%\host\build\libhackrf\src\Release\* %APPVEYOR_BUILD_FOLDER%\host\build\hackrf-tools\src\Release\* 

artifacts:
  - path: HackRF-Windows-experimental.zip
    name: HackRF-Windows-experimental
